import requests
import time
from bs4 import BeautifulSoup

def check_website(url):
    print(f"\n🌐 Checking: {url}")
    print("-" * 40)

    try:
        start = time.time()
        response = requests.get(url, timeout=10)
        end = time.time()

        speed = round(end - start, 2)
        status = response.status_code

        if status == 200:
            print(f"✅ Status  : {status} — Website is UP")
        else:
            print(f"⚠️  Status  : {status} — Something is wrong")

        print(f"⚡ Speed   : {speed} seconds")
        
        ssl_secure = check_ssl(url)
        headers_score = check_headers(url)
        broken_count = check_broken_links(url)

        save_pdf_report(url, status, speed, ssl_secure, headers_score, broken_count)

    except requests.exceptions.ConnectionError:
        print("❌ ERROR: Cannot reach the website")
    except requests.exceptions.Timeout:
        print("❌ ERROR: Website took too long to respond")

def check_ssl(url):
    if url.startswith("https://"):
        print("🔒 SSL     : Secure ✅")
        return True
    else:
        print("⚠️  SSL     : Not Secure ❌")
        return False

def check_headers(url):
    try:
        response = requests.get(url, timeout=10)
        headers = response.headers

        print("\n🛡️  Security Headers:")

        checks = {
            "X-Frame-Options": "Clickjacking Protection",
            "X-XSS-Protection": "XSS Protection",
            "Strict-Transport-Security": "HTTPS Enforced",
            "Content-Security-Policy": "Content Security"
        }

        score = 0
        for header, description in checks.items():
            if header in headers:
                print(f"   ✅ {description}")
                score += 1
            else:
                print(f"   ❌ {description} — Missing!")

        print(f"\n   Score: {score}/4")
        return score

    except:
        return 0

def check_broken_links(url):
    try:
        response = requests.get(url, timeout=10)
        soup = BeautifulSoup(response.text, "html.parser")
        links = soup.find_all("a")

        print(f"\n🔗 Broken Links Check:")
        broken = 0

        for link in links:
            href = link.get("href")
            if href and href.startswith("http"):
                try:
                    r = requests.get(href, timeout=5)
                    if r.status_code == 404:
                        print(f"  ❌ BROKEN: {href}")
                        broken += 1
                except:
                    print(f"  ⚠️  UNREACHABLE: {href}")
                    broken += 1

        if broken == 0:
            print("  ✅ No broken links found!")
        else:
            print(f"\n  Total broken: {broken}")

            return broken

    except:
        print("❌ Could not check links")
        
        return 0 

def save_pdf_report(url, status, speed, ssl_secure, headers_score, broken_count):
    from fpdf import FPDF
    from datetime import datetime

    pdf = FPDF()
    pdf.add_page()

    # --- Header ---
    pdf.set_fill_color(30, 30, 30)
    pdf.rect(0, 0, 210, 30, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 30, "  Website Security Report", ln=True)

    # --- Date ---
    pdf.set_text_color(100, 100, 100)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.ln(5)

    # --- URL ---
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Target: {url}", ln=True)
    pdf.ln(3)

    # --- Results ---
    def add_row(label, value, good=True):
        color = (0, 150, 0) if good else (200, 0, 0)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(70, 9, label)
        pdf.set_text_color(*color)
        pdf.cell(0, 9, str(value), ln=True)

    add_row("Status:", f"{status} - UP" if status == 200 else f"{status} - Issue", status == 200)
    add_row("Speed:", f"{speed} seconds", speed < 2)
    add_row("SSL:", "Secure" if ssl_secure else "Not Secure", ssl_secure)
    add_row("Security Headers:", f"{headers_score}/4", headers_score >= 3)
    add_row("Broken Links:", f"{broken_count} found", broken_count == 0)

    # --- Footer ---
    pdf.ln(10)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_text_color(150, 150, 150)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 8, "Generated by hsec-dev-max | Website Security Checker", ln=True)

    filename = f"report_{url.replace('https://', '').replace('http://', '').replace('/', '_')}.pdf"
    pdf.output(filename)
    print(f"\n📄 Report saved: {filename}")

# --- Main ---
while True:
    url = input("\nEnter website URL (or 'quit' to exit): ")
    if url == "quit":
        break
    if not url.startswith("http"):
        url = "https://" + url
    check_website(url)